# Generated by Django 2.2.3 on 2019-07-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarBarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=255)),
                ('nama', models.CharField(max_length=50)),
                ('harga', models.CharField(max_length=50)),
            ],
        ),
    ]
