# Generated by Django 2.2.3 on 2019-07-25 04:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DAFTAR_BARANG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftarbarang',
            name='moto',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
